### ISSUE TITLE
[pages] Role Pages

### ISSUE THREAD

**Issue by wcrum** [marinecoders/mcswf#1]
## Summary
Following the figma design, there needs to be 4 pages for the 4 roles. 
1. Software Engineer
2. Product Designer
3. Product Manager
4. Platform Engineer

Assignee: @dritter44

Given that each of the 4 pages are similar in layout, the goal is to create 4 static pages generated with props that populate the content on the page.

Given page 3 on the role is the cohort section see #2 related to the separate progress of the individual component.

## Screenshot
![Screenshot 2023-10-19 at 13 00 33](https://github.com/marinecoders/mcswf/assets/30413278/4783b6da-3c63-4bad-97b0-49ed89dde60f)

**Comment by scottpiercew** [comment]
The four roles are described in content/roleDetails/
