### ISSUE TITLE
[enhancement] Mobile Layout and Padding

### ISSUE THREAD

**Issue by wcrum** [marinecoders/mcswf#13]
Currently the site has multiple overlapping / overflow issues when it comes to mobile. Goal is to make mobile a first class citizen, this will take modifying padding, margin, and content sizes.

Labelled as a bug and enhancement due to the fact that this is a visual bug.

![Screenshot 2023-10-31 at 00 39 00](https://github.com/marinecoders/mcswf/assets/30413278/9f57addd-f709-492c-b118-481a4b6f8d84)
![Screenshot 2023-10-31 at 00 38 54](https://github.com/marinecoders/mcswf/assets/30413278/f2ac6365-f199-4dc5-af95-25f47b87914f)

**Comment by whalenda** [comment]
![image](https://github.com/marinecoders/mcswf/assets/23217615/3c6c86ee-229c-449f-a6cc-4d00aee660cf)


https://github.com/marinecoders/mcswf/assets/23217615/2e267a29-0dd3-48d3-a7fd-deb59986fa3b

![image](https://github.com/marinecoders/mcswf/assets/23217615/71a1a6b6-fb71-4483-b7dd-6c6dfd9683ec)

![image](https://github.com/marinecoders/mcswf/assets/23217615/30a24d6b-66fd-4107-a19f-ae83be3f1108)

![image](https://github.com/marinecoders/mcswf/assets/23217615/cf8ba5a8-f126-4c1e-bca1-3e3c32d90e9e)

**Comment by SemperRuminare** [comment]
I'm still seeing overlapping on safari iOS.

iOS: 17.4
Device: iPhone 14 Pro

![image](https://github.com/marinecoders/mcswf/assets/2375683/08a08a85-11b4-406c-9490-29c108ef0a11)

![image](https://github.com/marinecoders/mcswf/assets/2375683/51dca043-7061-40dc-b32a-0aaeefc26021)
