### ISSUE TITLE
[enhancement] add linter and formatter

### ISSUE THREAD

**Issue by wcrum** [marinecoders/mcswf#25]

**Comment by scottpiercew** [comment]
I added Eslint and a pre-commit hook to run the linter.
npm install. Test Eslint is set up by running npx eslint <test_file.js>. If the file is not linted set up Eslint with npm init @eslint/config@latest
npx husky init after running this command you will see package.json has a test script and there will be a pre-commit file under .husky. Add npx lint-staged to the pre-commit file.
In VS Code settings.json, add "eslint.validate": ["javascript", "javascriptreact", "svelte"] to tell eslint the type of files to look at.
With the pre-commit hook created and eslint set up, each time you make a commit with a file type from above staged the pre-commit hook will lint the code.
